export const ERROR_CODES = Object.freeze({
  INVALID_INPUT: Object.freeze({ code: 'INVALID_INPUT', statusCode: 400, message: 'Los datos enviados no son válidos.' }),
  INVALID_ID: Object.freeze({ code: 'INVALID_ID', statusCode: 400, message: 'El identificador enviado no es válido.' }),
  INVALID_ROLE: Object.freeze({ code: 'INVALID_ROLE', statusCode: 400, message: 'El rol indicado no es válido.' }),
  INVALID_PRODUCT_STATUS: Object.freeze({ code: 'INVALID_PRODUCT_STATUS', statusCode: 400, message: 'El estado de producto indicado no es válido.' }),
  INVALID_ORDER_STATUS: Object.freeze({ code: 'INVALID_ORDER_STATUS', statusCode: 400, message: 'El estado del pedido indicado no es válido.' }),
  INVALID_ORDER_PRIORITY: Object.freeze({ code: 'INVALID_ORDER_PRIORITY', statusCode: 400, message: 'La prioridad del pedido indicada no es válida.' }),
  INVALID_DELIVERY_STATUS: Object.freeze({ code: 'INVALID_DELIVERY_STATUS', statusCode: 400, message: 'El estado de la entrega indicado no es válido.' }),
  INVALID_MOCK_COUNTS: Object.freeze({ code: 'INVALID_MOCK_COUNTS', statusCode: 400, message: 'Las cantidades solicitadas para los mocks no son válidas.' }),
  MOCK_USERS_REQUIRED: Object.freeze({ code: 'MOCK_USERS_REQUIRED', statusCode: 400, message: 'Para generar pedidos debe existir al menos un usuario.' }),
  USER_NOT_FOUND: Object.freeze({ code: 'USER_NOT_FOUND', statusCode: 404, message: 'Usuario no encontrado.' }),
  PRODUCT_NOT_FOUND: Object.freeze({ code: 'PRODUCT_NOT_FOUND', statusCode: 404, message: 'Producto no encontrado.' }),
  ORDER_NOT_FOUND: Object.freeze({ code: 'ORDER_NOT_FOUND', statusCode: 404, message: 'Pedido no encontrado.' }),
  DELIVERY_NOT_FOUND: Object.freeze({ code: 'DELIVERY_NOT_FOUND', statusCode: 404, message: 'Entrega no encontrada.' }),
  DRIVER_NOT_FOUND: Object.freeze({ code: 'DRIVER_NOT_FOUND', statusCode: 404, message: 'Repartidor no encontrado.' }),
  ROUTE_NOT_FOUND: Object.freeze({ code: 'ROUTE_NOT_FOUND', statusCode: 404, message: 'La ruta solicitada no existe.' }),
  EMAIL_ALREADY_EXISTS: Object.freeze({ code: 'EMAIL_ALREADY_EXISTS', statusCode: 409, message: 'El email ya está registrado.' }),
  PRODUCT_CODE_ALREADY_EXISTS: Object.freeze({ code: 'PRODUCT_CODE_ALREADY_EXISTS', statusCode: 409, message: 'Ya existe un producto con ese código.' }),
  TRACKING_CODE_ALREADY_EXISTS: Object.freeze({ code: 'TRACKING_CODE_ALREADY_EXISTS', statusCode: 409, message: 'Ya existe un pedido con ese código de seguimiento.' }),
  DELIVERY_ALREADY_EXISTS: Object.freeze({ code: 'DELIVERY_ALREADY_EXISTS', statusCode: 409, message: 'El pedido ya tiene una entrega asociada.' }),
  DUPLICATE_RESOURCE: Object.freeze({ code: 'DUPLICATE_RESOURCE', statusCode: 409, message: 'El registro ya existe.' }),
  MOCK_INSERTION_FAILED: Object.freeze({ code: 'MOCK_INSERTION_FAILED', statusCode: 500, message: 'No se pudieron insertar los datos de prueba.' }),
  FILE_REQUIRED: Object.freeze({ code: 'FILE_REQUIRED', statusCode: 400, message: 'Debe enviar un archivo.' }),
  INVALID_FILE_TYPE: Object.freeze({ code: 'INVALID_FILE_TYPE', statusCode: 400, message: 'El tipo de archivo no está permitido.' }),
  FILE_TOO_LARGE: Object.freeze({ code: 'FILE_TOO_LARGE', statusCode: 413, message: 'El archivo supera el tamaño máximo permitido.' }),
  INVALID_DOCUMENT_TYPE: Object.freeze({ code: 'INVALID_DOCUMENT_TYPE', statusCode: 400, message: 'El tipo de documento indicado no es válido.' }),
  UNEXPECTED_FILE_FIELD: Object.freeze({ code: 'UNEXPECTED_FILE_FIELD', statusCode: 400, message: 'El campo de archivo enviado no coincide con el esperado.' }),
  FILE_SAVE_ERROR: Object.freeze({ code: 'FILE_SAVE_ERROR', statusCode: 500, message: 'No se pudo guardar o asociar el archivo.' }),
  INTERNAL_ERROR: Object.freeze({ code: 'INTERNAL_ERROR', statusCode: 500, message: 'Error interno del servidor.' }),
});
